version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID='CLIENT_ID'
      - REACT_APP_BACKEND_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL='MONGO_ID'
      - ACCESS_TOKEN_SECRET='SECRET_KEY'
